In [1]:
import numpy as np

In [6]:
np.random.randn(2,2)

array([[-1.89202519,  0.41443583],
       [ 0.06670099, -0.01034403]])

In [8]:
arr = np.arange(25)
rarr = np.random.randint(0,50,10)

In [9]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [10]:
rarr

array([27, 17,  5, 16, 33, 18, 39,  9, 20, 29])

In [14]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [12]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [17]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [18]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))


In [19]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [23]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])